### ISSUE TITLE
Padlistener does not sync

### ISSUE THREAD

**Issue by bozz514** [Neraud/PADListener#100]
I have followed the instructions on the youtube video on getting everything set up, currently using auto proxy but when i launch PAD through the app, it will not sync even past the start page, there is no actions. tried manually entering the proxy in the wifi settings and no dice

PAD US 8.6.2
Phone: Nexus 5 android 6.0.1 stock rom

**Comment by Neraud** [comment]
The AutoProxy mode is broken with Android 6.
AutoIPTables should still work.

In the next version (2.1.9), I've added a proper message and ManualProxy is fixed (since #97)
