### ISSUE TITLE
Ignore PADherder 'jp_only' flag

### ISSUE THREAD

**Issue by madcowfred** [Neraud/PADListener#71]
As per title, just add monsters even if the PADherder data claims JP only. Nothing on PADherder's end actually cares if they are or not, it just means I get "X's name is in Japanese" reports rather than PADLISTENER DON'T WORK :person_frowning:

**Comment by JamesCID** [comment]
And I'm  one of the buggers reporting  those  issues,  so I second it.

**Comment by Neraud** [comment]
I added the jp_only check to prevent issues with monsters being released in JP with ids already used in NA (I still have nightmares about the BAO monsters ;p). In this case, I suppose the monsters will first be created with only an id_jp and jp_only = true, and then it would be updated with an id_us and jp_only = false.
But it seems it's causing issues to prevent something that should not happen.

I'll remove it.
