### ISSUE TITLE
IOS

### ISSUE THREAD

**Issue by ryantheleach** [Neraud/PADListener#77]
You mention in the demo video that the listener doesn't work on IOS. Is there a technical reason for this, or have you just not attempted to parse the data sent from IOS devices?

I'm interested because I'm attempting to do something similar for another game.

**Comment by Neraud** [comment]
Initially, I thought it would work. As I do not own any iOS device, I could not test it myself.

Unfortunately, on iOS, there's an issue with PAD not using the OS-level settings. It's documented on the posts explaining how to use padproxy.py ([here](http://www.reddit.com/r/PuzzleAndDragons/comments/26m867/guide_to_using_padproxypy_an_easier_way_to_sync/) and [here](http://www.reddit.com/r/PuzzleAndDragons/comments/2aprue/guide_how_to_update_padherder_for_ios/) for example).

padproxy.py works by also starting a DNS server. I suppose PADListener would also work if I manage to start a DNS server on the Android device.

**Comment by ryantheleach** [comment]
Thanks for the help, hopefully my game uses the os specific settings.
