### ISSUE TITLE
Cant get PADListener to capture

### ISSUE THREAD

**Issue by guigui-ln** [Neraud/PADListener#80]
Hello, I cant get PADListener to capture data at PAD launch, details :

I used both manual and auto wifi mode, I see the internet connection turn off and on and check that my proxy is correctly set : localhost, port 8008. Then I launch PAD (manual capture) or autolanch (auto capture) and wait at the title screen, but the capture does not start.

Other facts :
- PADListener version 2.1.1 gotten from playstore
 - PAD NA version 7.3.0. Since I live in EU and the game is not available here, I had to download the .apk file and install it manually.
- When the proxy is set, I cant access the web via my browser, it says : "unable to connect to the proxy server". I can play to PAD though.

Any help will be grandly appreciated.

**Comment by Neraud** [comment]
PAD fetches data from GungHo's servers when you hit START on the title screen.
Did you try to go through the title screen into the game while the listener is active ?

**Comment by guigui-ln** [comment]
Yes I surely did, sorry for mis-explanation in the first post.
I did try about everything that came to my mind (manual proxy, auto proxy, manual capture, auto capture, wait a lot, uninstall and reinstall PADListener, ...) but nope, it does not catch data.
I certainly appreciate your help though, any idea ?

**Comment by guigui-ln** [comment]
Yes I surely did, sorry for mis-explanation in the first post.
I did try about everything that came to my mind (manual proxy, auto proxy, manual capture, auto capture, wait a lot, uninstall and reinstall PADListener, ...) but nope, it does not catch data.
I certainly appreciate your help though, any idea ?
      De : Neraud <notifications@github.com>
 À : Neraud/PADListener <PADListener@noreply.github.com> 
Cc : guigui-ln <coqguilhem@yahoo.fr> 
 Envoyé le : Dimanche 5 avril 2015 16h00
 Objet : Re: [PADListener] Cant get PADListener to capture (#80)
   
PAD fetches data from GungHo's servers when you hit START on the title screen.
Did you try to go through the title screen into the game while the listener is active ?—

**Comment by guigui-ln** [comment]
So I did try some other stuff to capture my data but still cant do it.
Is it normal that, while the proxy is on, I cant access the internet via my browser (Chrome) ? I can still play PAD and other online games though.
Anyway, a PAD update is on its way to the US server, so I'll just try again with the new PAD version and let you know.

**Comment by rbuttiero** [comment]
Using the Auto Iptables mode, the Listener should not have any impact on any other app.

Using the Proxy Mode, all HTTP and HTTPS request go through the proxy. Only request sent to GungHo's servers are processed, but all request still go through the proxy. HTTP requests should not be impacted. When your browser sends a request to https://foo.bar, the proxy answers with a generated HTTPS certificate that does not match foo.bar. Any properly coded app should refuse this certificate as it's detected as a [Man-in-the-middle attack](http://en.wikipedia.org/wiki/Man-in-the-middle_attack).


To investigate your capture issue : can you check in PADListener's settings > Listener > Target servers if your region is selected ?

**Comment by Neraud** [comment]
Using the Auto Iptables mode, the Listener should not have any impact on any other app.

Using the Proxy Mode, all HTTP and HTTPS request go through the proxy. Only request sent to GungHo's servers are processed, but all request still go through the proxy. HTTP requests should not be impacted. When your browser sends a request to https://foo.bar, the proxy answers with a generated HTTPS certificate that does not match foo.bar. Any properly coded app should refuse this certificate as it's detected as a Man-in-the-middle attack.

To investigate your capture issue : can you check in PADListener's settings > Listener > Target servers if your region is selected ?

**Comment by guigui-ln** [comment]
Thanks for the explanation. I could not try Auto Iptables mode since my device is not rooted by the way.

Target servers are all set in the settings. I tried to set only NA version, with no success.
Now that I think about it, I did not try to set each server separately and will do it soon.

I also tried to set a custom server name (that includes "padsv" insted of "pad" as you mentionned in some other post). No success either.

As said earlier, I installed PAD 7.3.0 via the .apk package since it is not available here in France. Title screen says my PAD is NA version, may the irregular installation create my issue ?

**Comment by Neraud** [comment]
Nope. I'm in France too and had to use a VPN to install the NA version. I've tested the JP and KO versions installed from APK files and everything works.

You can check if you manage to capture data with [SandroProxy](https://play.google.com/store/apps/details?id=org.sandroproxy). 
- Start SandroProxy, with "Developers mode, capture data". It should display logs lines "Proxy listening on 127.0.0.1:8008" and a few others. 
- Manually set your Wifi proxy to localhost:8008
- Launch PAD and go through the title page
- Go back to SandroProxy in the HTTP tab

If the capture works, you should see a few calls to https://api-na-adr.padsv.gungho.jp//api.php. If that works, the capture with the core proxy from SandroProxy works. PADListener is based on this core, so it should also capture correctly

(when done, remember to stop SandroProxy and disable your Wifi proxy ;p)

**Comment by guigui-ln** [comment]
SandroProxy starts correctly, listening to 127.0.0.1:8008.
I manually set proxy to localhost:8008, launch PAD, go through title screen.

SandroProxy says "no data" in the HTTP tab. Looks like nothing is captured at all.

**Comment by Neraud** [comment]
Just to be sure, the proxy settings are : 
- Proxy hostname : localhost
- Proxy port : 8008
- Bypass proxy for : [empty]

You might need to hit the refresh button in the HTTP tab to show the captured request.

Without root and special configuration, SandroProxy should capture everything.
For example, if you try to use your browser, any http request should be logged, and https request should raise a certificate warning.

**Comment by guigui-ln** [comment]
My proxy settings look correct.
The Bypass proxy for field says 'example.com,mycomp.test,localhost', which is automatically written when I delete everything.
Additional info : IP setting is DHCP, Security is WPA/WPA2 PSK.

But SandroProxy does not capture anything : no PAD launch, no browser traffic, even though I hit the refresh button.

Also, that difference you mention between http and https request, I dont see it. Any site I try to connect to, the browser says :

Unable to connect to proxy server.
Right now your system is configured to use a proxy, but Google Chrome cant connect to it.
Error_code : ERR_PROXY_CONNECTION_FAILED  <-- Scary caps !

**Comment by Neraud** [comment]
The scary caps error means some proxy settings are wrong.
You can try to set the proxy to 127.0.0.1 instead of localhost.

What kind of Wifi are you using ? I mean, is it your home Wifi, or a school / work Wifi ?

Stop SandroProxy and PADListener. Set your Wifi proxy to None. Is internet still working (in Chrome for example) ? Set it to Proxy Auto-Config if you can (I have the option in 5.0 but not 4.4). How about now ?

**Comment by guigui-ln** [comment]
Well, 127.0.0.1 looks good !
SandroProxy sees some traffic through this proxy setting, Chrome reacts correctly : displays http sites, blicks https sites.

PADListener captured my data, nice !
I have to set the proxy manually though, since PADListener automatically set it to localhost, right ? 

Afterwards, I have to unset it to allow sync with PADHerder.

So, in my case, this is not as automatic as one wish, but it works. Thanks for the precious help and time you gave me.

**Comment by Neraud** [comment]
So 127.0.0.1 works and localhost doesn't ? Weird !
I'll change the auto wifi proxy mode to use 127.0.0.1 then.

Glad you could finally sync ;p

**Comment by guigui-ln** [comment]
That's right, 127.0.0.1 is ok, localhost is not.
By the way, I use home wifi, brand new livebox by FAI Sosh.
So you'll release an update for PADListener that uses 127.0.0.1 ?
