### ISSUE TITLE
PADListener not capturing JP

### ISSUE THREAD

**Issue by gaminghermit** [Neraud/PADListener#82]
I just downloaded PADListener tonight and set it up. It worked fine for NA server but nothing happened when I tried JP server. My phone is not rooted. I used PADListener before in the past and it worked fine for JP server.

**Comment by Kinglink** [comment]
Same here.  My guess is that pad changed the server on the Japanese game but would love to hear get confirmation from Neraud or the new address

**Comment by Neraud** [comment]
The server has indeed changed again (api-adr.padsv.gungho.jp -> api-adrv2.padsv.gungho.jp)

But that's not all, the data format has also been modified (from JSON associative arrays to JSON arrays). This change is only present on JP at the moment it seems, so I need to keep 2 versions of the parser.
