### ISSUE TITLE
Unable to capture data from Japanese version

### ISSUE THREAD

**Issue by Ekip** [Neraud/PADListener#92]
Since Japan last update I've been unable to get my data captured using padlistener.

The current android version I use is 5.0.1 The device is a Samsung Galaxy S4 GT-I9505

Here i link you a screenshot when the problem happens.
http://i.imgur.com/3RGLUTy.png
Any ideas on how to solve this?

**Comment by sionar** [comment]
I am getting the same issue on a Google Nexus 5, with the same error message when I open the JP client. Padlistener is able to capture NA without issues.

**Comment by Neraud** [comment]
I've checked on my Nexus7 (running Android 6) and it works using Manual Proxy.
Could you please test again with the soon-to-be-released 2.1.9 ?

**Comment by Ekip** [comment]
Trying to use the manual mode but I have no clue on how make it work, could you explain it here so I can test if the capturing works with JP again?

**Comment by Ekip** [comment]
Nevermind, got it to work with a friend in the Discord chat. Ty for solving it!
